name: Notify Discord on Push

on:
  push:
    branches:
      - main
      - sheree  # add your branch name here too if you want

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"🚀 New push by $GITHUB_ACTOR to *$GITHUB_REPOSITORY* on branch *$GITHUB_REF_NAME*!\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
